# Matemática para Ciencia de los Datos
# Quiz 1

## Estudiante: Sergio Fernández Calvo

Luis Alexánder Calvo Valverde 

Instituto Tecnológico de Costa Rica, 

PAttern Recongition and MAchine Learning Group (PARMA-Group)

---

Fecha de entrega: Jueves 19 de Marzo del 2020, a más tardar a las 3:00 pm.

Medio de entrega: Por medio del TEC-Digital.

Entregables: Un archivo en jupyter ( .IPYNB ). 

Modo de trabajo: Individual.


---



Resumen En el presente quiz se repasan varios conceptos elementales respecto a matrices.


---


**Pregunta 1**

Considerando que la transpuesta de una matriz es el resultado de cambiar las filas a columnas. Sea una matriz $A\in\mathbb{R}^{m\times n}$, su transpuesta se escribe como $A^{T}\in\mathbb{R}^{n\times m}$ y sus entradas están dadas por: 

\begin{equation}
\left(A^{T}\right)_{i,j}=A_{j,i}.
\end{equation}

Las siguientes son propiedades de la transpuesta: 

- $\left(A^{T}\right)^{T}=A$
- $\left(AB\right)^{T}=B^{T}A^{T}$
- $\left(A+B\right)^{T}=A^{T}+B^{T}$.



---



Proponga Usted dos matrices, $A\in\mathbb{R}^{4\times 3}$ y $B\in\mathbb{R}^{3\times 4}$ (no las busque en Internet, trate de proponer los valores por si mismo), y utilizando pythorch muestre que las siguientes propiedades se cumplen con sus matrices propuestas.

**Note** que ni A ni B son cuadradas, y no tienen las mismas dimensiones.


**1. (15 puntos)**

$\left(A^{T}\right)^{T}=A$

**2. (15 puntos)**

$\left(AB\right)^{T}=B^{T}A^{T}$



In [4]:
## Solución 
import torch as torch
import math
import numpy as np

Sean  \begin{equation}
A=\begin{bmatrix}
1 & 3 & 5 \\
7 & 9 & 11 \\
1 & 3 & 5 \\
7 & 9 & 11
\end{bmatrix}, 
\qquad
B=\begin{bmatrix}
2 & 4 & 6 & 8 \\
10 & 12 & 14 & 16\\
2 & 4 & 6 & 8\\
\end{bmatrix}
\end{equation}

In [40]:
#crear a
a = torch.arange(1, 13, 2)
a = torch.reshape(a, (2,3)).repeat(2,1)
a

tensor([[ 1,  3,  5],
        [ 7,  9, 11],
        [ 1,  3,  5],
        [ 7,  9, 11]])

In [63]:
#crear b 
b = torch.arange(2, 18, 2)
b = torch.reshape(b, (2, 4)).repeat(2,1)
b = b[:-1]
b


tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16],
        [ 2,  4,  6,  8]])

**1. (15 puntos)** Solución

$\left(A^{T}\right)^{T}=A$

In [71]:
torch.equal(a, torch.t(torch.t(a)))

True

**2. (15 puntos)**

$\left(AB\right)^{T}=B^{T}A^{T}$

In [76]:
torch.equal(torch.t(torch.mm(a, b)), torch.mm(torch.t(b), torch.t(a)))

True

**Pregunta 2**


Un conjunto de vectores $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \in\mathbb{R}^{m}$ se dice que es linealmente independiente, si ningún vector de tal conjunto puede ser representado como una combinación lineal del resto de vectores. De lo contrario, si uno de los vectores en tal conjunto puede ser representado como una combinación lineal del resto de vectores, entonces los vectores son linealmente dependientes, lo que se expresa como: 

\begin{equation}
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
\end{equation}

para cualquier conjunto de valores escalares $\alpha_{1},\ldots,\alpha_{n-1}\in\mathbb{R}$ se dice que el vector $\vec{x}_{j}\in\mathbb{R}^{m}$ es linealmente dependiente de los vectores $\vec{x}_{i}$. 



---

**1. (20 puntos)**

Proponga una matriz $A\in\mathbb{R}^{5\times 5}$, propóngala Usted mismo (no la busque en Internet) y que no sea la matriz identidad, de manera que dicha matriz sea de rango completo. Muestre en pytorch que cumple esta propiedad (puede usar matrix_rank).

**2. (20 puntos)**
Ahora hágale cambios a su matriz de manera que sea de rango $3$, y luego más cambios para que sea de rango $2$. Muestre como va cambiando la matriz y el cálculo del rango en pythorch (puede utilizar torch.matrix_rank).

**Solución**

In [96]:
a = 
print(torch.matrix_rank(a))
a

tensor(2)


tensor([[ 1.,  2.,  3.,  4.,  5.],
        [ 6.,  7.,  8.,  9., 10.],
        [11., 12., 13., 14., 15.],
        [16., 17., 18., 19., 20.],
        [21., 22., 23., 24., 25.]], dtype=torch.float64)

**Pregunta 3 (30 puntos)**

Programe en python una función llamada esOrtonormal, que reciba un parámetro llamado pMatriz y retorna True si pMatriz es una matriz ortonormal y False de lo contrario. Como pre-condición considere que la matriz tiene al menos 2 filas y 2 columnas.

def esOrtonormal( pMatriz ):

**Nota: ** Como requerirá calcular las combinaciones, investigue el uso del siguiente código. El 5 es solo un ejemplo, sería el número total de elementos a combinar:

```
from itertools import combinations 

filas = 5

combinaciones = combinations(list(range(filas)), 2)

for una in list(combinaciones): 

 print(una)



